In [10]:
import pandas as pd

In [11]:
deng_dados14 = pd.read_csv('./data/DENGBR14.csv')

C:\Users\vrevy\AppData\Local\Temp\ipykernel_12304\2085267701.py:1: DtypeWarning: Columns (22,50,52,54,56,62,74) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados14 = pd.read_csv('./data/DENGBR14.csv')

In [30]:
deng_dados14.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI
0,2,A90,2014-05-17,201420,2014,12,120040,1938.0,6439837.0,2014-05-10,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
1,2,A90,2014-07-09,201428,2014,12,120040,1938.0,2001578.0,2014-07-04,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
2,2,A90,2014-09-03,201436,2014,12,120020,1941.0,2000318.0,2014-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
3,2,A90,2014-10-13,201442,2014,12,120020,1941.0,2000172.0,2014-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
4,2,A90,2014-03-28,201413,2014,12,120040,1938.0,2001527.0,2014-03-23,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN

In [13]:
print(deng_dados14.columns)

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI',
       ...
       'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD',
       'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'CS_FLXRET', 'FLXRECEBI'],
      dtype='object', length=119)

In [14]:
deng_dados14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 966619 entries, 0 to 966618
Columns: 119 entries, TP_NOT to FLXRECEBI
dtypes: float64(99), int64(6), object(14)
memory usage: 877.6+ MB

In [15]:
deng_dados14.RESUL_SORO.value_counts()

RESUL_SORO
4.0    426723
1.0    176759
2.0    158722
3.0      2621
Name: count, dtype: int64

In [27]:
deng_dados14.EVOLUCAO.value_counts()

EVOLUCAO
1.0    782620
9.0     39092
3.0      1142
2.0       500
4.0        85
Name: count, dtype: int64

In [17]:
deng_dados23 = pd.read_csv('./data/DENGBR23.csv')
deng_dados23.head()

C:\Users\vrevy\AppData\Local\Temp\ipykernel_12304\1986040255.py:1: DtypeWarning: Columns (21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados23 = pd.read_csv('./data/DENGBR23.csv')

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,20230101,202301,2023,12,120070,1937.0,2000393.0,20230101,...,NaN,NaN,NaN,NaN,2.0,NaN,20240111,1.0,NaN,NaN
1,2,A90,20230102,202301,2023,12,120005,1937.0,2001020.0,20230101,...,NaN,NaN,NaN,NaN,2.0,NaN,20230111,1.0,NaN,NaN
2,2,A90,20230102,202301,2023,12,120005,1937.0,2001020.0,20230101,...,NaN,NaN,NaN,NaN,2.0,NaN,20230111,1.0,NaN,NaN
3,2,A90,20230102,202301,2023,12,120030,1940.0,2000636.0,20230101,...,NaN,NaN,NaN,NaN,2.0,NaN,20230207,1.0,NaN,NaN
4,2,A90,20230102,202301,2023,12,120005,1937.0,2001020.0,20230102,...,NaN,NaN,NaN,NaN,2.0,NaN,20230112,1.0,NaN,NaN

In [31]:
deng_dados23.NU_IDADE_N.value_counts()

NU_IDADE_N
4023    30483
4022    30012
4025    29573
4026    29087
4021    28895
        ...
43          1
3           1
1041        1
2055        1
2067        1
Name: count, Length: 281, dtype: int64

In [28]:
pd.concat([ deng_dados14, deng_dados23])

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W
0,2,A90,2014-05-17,201420,2014,12,120040,1938.0,6439837.0,2014-05-10,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
1,2,A90,2014-07-09,201428,2014,12,120040,1938.0,2001578.0,2014-07-04,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
2,2,A90,2014-09-03,201436,2014,12,120020,1941.0,2000318.0,2014-09-01,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
3,2,A90,2014-10-13,201442,2014,12,120020,1941.0,2000172.0,2014-10-11,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
4,2,A90,2014-03-28,201413,2014,12,120040,1938.0,2001527.0,2014-03-23,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508648,2,A90,20231228,202352,2023,17,172120,NaN,9038701.0,20231226,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1986.0,20240104,NaN
1508649,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1984.0,20231229,NaN
1508650,2,A90,20231229,202352,2023,17,170820,NaN,2546728.0,20231225,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1971.0,20240119,NaN
1508651,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1996.0,20231229,NaN
1508652,2,A90,20231229,202352,2023,17,172100,NaN,5144175.0,20231222,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1959.0,20231229,NaN