## Inicio do projeto

Como os arquivos ja foram convertidos em csv, vou fazer a leitura de cada csv e separar os dados de Ilhéus e Itabuna

In [2]:
import pandas as pd

### Ler e salvar dados de 2014 a 2019

In [ ]:
# Ler dados de 2014 a 2019
deng_dados14 = pd.read_csv('./data/DENGBR14.csv')
deng_dados15 = pd.read_csv('./data/DENGBR15.csv')
deng_dados16 = pd.read_csv('./data/DENGBR16.csv')
deng_dados17 = pd.read_csv('./data/DENGBR17.csv')
deng_dados18 = pd.read_csv('./data/DENGBR18.csv')
deng_dados19 = pd.read_csv('./data/DENGBR19.csv')

In [ ]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2014 a 19
codigo_ilheus_itabna = [291360,291480]

deng_dados14_ba = deng_dados14[deng_dados14['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados15_ba = deng_dados15[deng_dados15['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados16_ba = deng_dados16[deng_dados16['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados17_ba = deng_dados17[deng_dados17['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados18_ba = deng_dados18[deng_dados18['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados19_ba = deng_dados19[deng_dados19['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [ ]:
# Salvar novos csvs de 14 a 19
deng_dados14_ba.to_csv('data-filtred/deng_dados14_ba.csv', index=False)
deng_dados15_ba.to_csv('data-filtred/deng_dados15_ba.csv', index=False)
deng_dados16_ba.to_csv('data-filtred/deng_dados16_ba.csv', index=False)
deng_dados17_ba.to_csv('data-filtred/deng_dados17_ba.csv', index=False)
deng_dados18_ba.to_csv('data-filtred/deng_dados18_ba.csv', index=False)
deng_dados19_ba.to_csv('data-filtred/deng_dados19_ba.csv', index=False)

### Ler dados de 2020 a 2022

In [ ]:

deng_dados20 = pd.read_csv('./data/DENGBR20.csv')
deng_dados21 = pd.read_csv('./data/DENGBR21.csv')
deng_dados22 = pd.read_csv('./data/DENGBR22.csv')

/tmp/ipykernel_49186/2725715471.py:3: DtypeWarning: Columns (9,21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados22 = pd.read_csv('./data/DENGBR22.csv')

In [ ]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2020 a 22
codigo_ilheus_itabna = [291360,291480]

deng_dados20_ba = deng_dados20[deng_dados20['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados21_ba = deng_dados21[deng_dados21['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados22_ba = deng_dados22[deng_dados22['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [ ]:
# Salvar novos csvs de 14 a 19
deng_dados20_ba.to_csv('data-filtred/deng_dados20_ba.csv', index=False)
deng_dados21_ba.to_csv('data-filtred/deng_dados21_ba.csv', index=False)
deng_dados22_ba.to_csv('data-filtred/deng_dados22_ba.csv', index=False)

### Ler dados de 2023

In [ ]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2023
codigo_ilheus_itabna = [291360,291480]
deng_dados23 = pd.read_csv('./data/DENGBR23.csv')

deng_dados23_ba = deng_dados23[deng_dados23['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados23_ba.to_csv('data-filtred/deng_dados23_ba.csv', index=False)

/tmp/ipykernel_49186/3690604613.py:3: DtypeWarning: Columns (21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados23 = pd.read_csv('./data/DENGBR23.csv')

In [13]:
deng_dados22_ba.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
42920,2,A90,20221222,202251,2022,29,291480,1385.0,2470330.0,20221211,...,NaN,NaN,NaN,NaN,2.0,NaN,20230124,NaN,NaN,NaN
42921,2,A90,20220420,202216,2022,29,291480,1385.0,2525569.0,20220415,...,NaN,NaN,NaN,NaN,2.0,NaN,20220504,NaN,NaN,NaN
42922,2,A90,20220420,202216,2022,29,291480,1385.0,2525569.0,20220415,...,NaN,NaN,NaN,NaN,2.0,NaN,20220427,NaN,NaN,NaN
42933,2,A90,20220714,202228,2022,29,291480,1385.0,2385171.0,20220707,...,NaN,NaN,NaN,NaN,2.0,NaN,20220830,NaN,NaN,NaN
43335,2,A90,20221213,202250,2022,29,291480,1385.0,2470330.0,20221119,...,NaN,NaN,NaN,NaN,2.0,NaN,20230124,NaN,NaN,NaN

### Ler dados de 2023

Como os dados de 2024 são muito grandes, foi necessario fazer a leitura por chunks, facilitando e consumindo menos memoria

In [11]:
chunks = pd.read_csv('./data/DENGBR24.csv', chunksize=100000, low_memory=False)
deng_dados24 = pd.concat(chunks)

In [ ]:
deng_dados24_ba = deng_dados24[deng_dados24['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [16]:
deng_dados24_ba.to_csv('data-filtred/deng_dados24_ba.csv', index=False)

### Dados

Algumas analises dos dados e do tipo de informaao contida nos dataframes

In [23]:
deng_dados24_ba.ID_MUNICIP.value_counts()

ID_MUNICIP
291360    3290
291480     645
Name: count, dtype: int64

In [17]:
print(deng_dados24_ba.columns)

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI',
       ...
       'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA',
       'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W'],
      dtype='object', length=121)

In [18]:
deng_dados24_ba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3935 entries, 11036 to 6363994
Columns: 121 entries, TP_NOT to MIGRADO_W
dtypes: float64(94), int64(10), object(17)
memory usage: 3.7+ MB

In [19]:
deng_dados24_ba.RESUL_SORO.value_counts()

RESUL_SORO
4.0    460
1.0    144
2.0      8
3.0      2
Name: count, dtype: int64

In [20]:
deng_dados24_ba.EVOLUCAO.value_counts()

EVOLUCAO
1.0    2149
9.0      12
3.0       4
2.0       1
Name: count, dtype: int64

In [11]:
pd.concat([ deng_dados14, deng_dados23])

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W
0,2,A90,2014-05-17,201420,2014,12,120040,1938.0,6439837.0,2014-05-10,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
1,2,A90,2014-07-09,201428,2014,12,120040,1938.0,2001578.0,2014-07-04,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
2,2,A90,2014-09-03,201436,2014,12,120020,1941.0,2000318.0,2014-09-01,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
3,2,A90,2014-10-13,201442,2014,12,120020,1941.0,2000172.0,2014-10-11,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
4,2,A90,2014-03-28,201413,2014,12,120040,1938.0,2001527.0,2014-03-23,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508648,2,A90,20231228,202352,2023,17,172120,NaN,9038701.0,20231226,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1986.0,20240104,NaN
1508649,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1984.0,20231229,NaN
1508650,2,A90,20231229,202352,2023,17,170820,NaN,2546728.0,20231225,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1971.0,20240119,NaN
1508651,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1996.0,20231229,NaN
1508652,2,A90,20231229,202352,2023,17,172100,NaN,5144175.0,20231222,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1959.0,20231229,NaN

In [7]:
from pysus import SINAN
sinan = SINAN().load() # Loads the files from DATASUS

In [9]:
codigo_ilheus_itabna = [291480,291360]
deng_dados14_ba = deng_dados14[deng_dados14['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados14_ba

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI
67512,2,A90,2014-07-07,201428,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67516,2,A90,2014-07-14,201429,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67517,2,A90,2014-04-23,201417,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67518,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67519,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92126,2,A90,2014-03-24,201413,2014,29,291480,1385.0,2772280.0,2014-03-22,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92138,2,A90,2014-03-31,201414,2014,29,291480,1385.0,2772280.0,2014-03-27,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92147,2,A90,2014-03-07,201410,2014,29,291360,1385.0,2415844.0,2014-03-04,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92172,2,A90,2014-03-20,201412,2014,29,291360,1385.0,2415844.0,2014-03-20,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,NaN
92226,2,A90,2014-03-18,201412,2014,29,291480,1385.0,2772280.0,2014-03-15,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN

In [15]:
# deng_dados23.NU_IDADE_N.value_counts()
# for cname in deng_dados23.columns:
#     if cname.startswith('DT_'):
#         deng_dados23[cname] = pd.to_datetime(deng_dados23[cname], errors='coerce')
#     elif cname.startswith('ID_'):
#         try:
#             deng_dados23[cname] = pd.to_numeric(deng_dados23[cname])
#         except ValueError:
#             continue
# deng_dados23.info()