## Inicio do projeto

Como os arquivos ja foram convertidos em csv, vou fazer a leitura de cada csv e separar os dados de Ilhéus e Itabuna

In [1]:
import pandas as pd

### Ler e salvar dados de 2014 a 2019

In [12]:
# Ler dados de 2014 a 2019
deng_dados14 = pd.read_csv('./data/DENGBR14.csv')
deng_dados15 = pd.read_csv('./data/DENGBR15.csv')
deng_dados16 = pd.read_csv('./data/DENGBR16.csv')
deng_dados17 = pd.read_csv('./data/DENGBR17.csv')
deng_dados18 = pd.read_csv('./data/DENGBR18.csv')
deng_dados19 = pd.read_csv('./data/DENGBR19.csv')

/tmp/ipykernel_2778/1487410978.py:2: DtypeWarning: Columns (22,50,52,54,56,62,74) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados14 = pd.read_csv('./data/DENGBR14.csv')
/tmp/ipykernel_2778/1487410978.py:3: DtypeWarning: Columns (9,21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados15 = pd.read_csv('./data/DENGBR15.csv')
/tmp/ipykernel_2778/1487410978.py:4: DtypeWarning: Columns (6,9,10,18,21,22,64,68,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados16 = pd.read_csv('./data/DENGBR16.csv')
/tmp/ipykernel_2778/1487410978.py:5: DtypeWarning: Columns (9,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados17 = pd.read_csv('./data/DENGBR17.csv')
/tmp/ipykernel_2778/1487410978.py:6: DtypeWarning: Columns (9,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados18 = pd.read_csv('./data/DENGBR18.csv')
/tmp/ipykernel_2778/1487410978.py:7: DtypeWarning: Columns (9,11,21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados19 = pd.read_csv('./data/DENGBR19.csv')

In [13]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2014 a 19
codigo_ilheus_itabna = [291360,291480]

deng_dados14_ba = deng_dados14[deng_dados14['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados15_ba = deng_dados15[deng_dados15['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados16_ba = deng_dados16[deng_dados16['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados17_ba = deng_dados17[deng_dados17['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados18_ba = deng_dados18[deng_dados18['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados19_ba = deng_dados19[deng_dados19['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [14]:
# Salvar novos csvs de 14 a 19
deng_dados14_ba.to_csv('data-filtred/deng_dados14_ba.csv', index=False)
deng_dados15_ba.to_csv('data-filtred/deng_dados15_ba.csv', index=False)
deng_dados16_ba.to_csv('data-filtred/deng_dados16_ba.csv', index=False)
deng_dados17_ba.to_csv('data-filtred/deng_dados17_ba.csv', index=False)
deng_dados18_ba.to_csv('data-filtred/deng_dados18_ba.csv', index=False)
deng_dados19_ba.to_csv('data-filtred/deng_dados19_ba.csv', index=False)

### Ler dados de 2020 a 2022

In [29]:

deng_dados20 = pd.read_csv('../data/nao-processado/DENGBR20.csv')
# deng_dados21 = pd.read_csv('./data/DENGBR21.csv')
# deng_dados22 = pd.read_csv('./data/DENGBR22.csv')

/tmp/ipykernel_39014/2551145349.py:1: DtypeWarning: Columns (9,21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados20 = pd.read_csv('../data/nao-processado/DENGBR20.csv')

In [30]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2020 a 22
codigo_ilheus_itabna = [291360,291480]

deng_dados20_ba = deng_dados20[deng_dados20['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
# deng_dados21_ba = deng_dados21[deng_dados21['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
# deng_dados22_ba = deng_dados22[deng_dados22['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [35]:
# Salvar novos csvs de 14 a 19
deng_dados20_ba.to_csv('../data/processado/deng_dados20_ba.csv', index=False)
# deng_dados21_ba.to_csv('data-filtred/deng_dados21_ba.csv', index=False)
# deng_dados22_ba.to_csv('data-filtred/deng_dados22_ba.csv', index=False)

### Ler dados de 2023

In [10]:
# Ler apenas os dados de ilhéus e itabuna do ano de 2023
codigo_ilheus_itabna = [291360,291480]
deng_dados23 = pd.read_csv('./data/DENGBR23.csv')

deng_dados23_ba = deng_dados23[deng_dados23['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados23_ba.to_csv('data-filtred/deng_dados23_ba.csv', index=False)

/tmp/ipykernel_10069/727904980.py:3: DtypeWarning: Columns (21,22,75) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados23 = pd.read_csv('./data/DENGBR23.csv')

In [11]:
deng_dados22_ba.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
42920,2,A90,20221222,202251,2022,29,291480,1385.0,2470330.0,20221211,...,NaN,NaN,NaN,NaN,2.0,NaN,20230124,NaN,NaN,NaN
42921,2,A90,20220420,202216,2022,29,291480,1385.0,2525569.0,20220415,...,NaN,NaN,NaN,NaN,2.0,NaN,20220504,NaN,NaN,NaN
42922,2,A90,20220420,202216,2022,29,291480,1385.0,2525569.0,20220415,...,NaN,NaN,NaN,NaN,2.0,NaN,20220427,NaN,NaN,NaN
42933,2,A90,20220714,202228,2022,29,291480,1385.0,2385171.0,20220707,...,NaN,NaN,NaN,NaN,2.0,NaN,20220830,NaN,NaN,NaN
43335,2,A90,20221213,202250,2022,29,291480,1385.0,2470330.0,20221119,...,NaN,NaN,NaN,NaN,2.0,NaN,20230124,NaN,NaN,NaN

### Ler dados de 2023

Como os dados de 2024 são muito grandes, foi necessario fazer a leitura por chunks, facilitando e consumindo menos memoria

In [11]:
chunks = pd.read_csv('./data/DENGBR24.csv', chunksize=100000, low_memory=False)
deng_dados24 = pd.concat(chunks)

In [ ]:
deng_dados24_ba = deng_dados24[deng_dados24['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

In [16]:
deng_dados24_ba.to_csv('data-filtred/deng_dados24_ba.csv', index=False)

### Dados

Algumas analises dos dados e do tipo de informacão contida nos dataframes

In [ ]:
pd

In [23]:
deng_dados24_ba.ID_MUNICIP.value_counts()

ID_MUNICIP
291360    3290
291480     645
Name: count, dtype: int64

In [17]:
print(deng_dados24_ba.columns)

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI',
       ...
       'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA',
       'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W'],
      dtype='object', length=121)

In [18]:
deng_dados24_ba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3935 entries, 11036 to 6363994
Columns: 121 entries, TP_NOT to MIGRADO_W
dtypes: float64(94), int64(10), object(17)
memory usage: 3.7+ MB

In [19]:
deng_dados24_ba.RESUL_SORO.value_counts()

RESUL_SORO
4.0    460
1.0    144
2.0      8
3.0      2
Name: count, dtype: int64

In [20]:
deng_dados24_ba.EVOLUCAO.value_counts()

EVOLUCAO
1.0    2149
9.0      12
3.0       4
2.0       1
Name: count, dtype: int64

In [11]:
pd.concat([ deng_dados14, deng_dados23])

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W
0,2,A90,2014-05-17,201420,2014,12,120040,1938.0,6439837.0,2014-05-10,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
1,2,A90,2014-07-09,201428,2014,12,120040,1938.0,2001578.0,2014-07-04,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
2,2,A90,2014-09-03,201436,2014,12,120020,1941.0,2000318.0,2014-09-01,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
3,2,A90,2014-10-13,201442,2014,12,120020,1941.0,2000172.0,2014-10-11,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
4,2,A90,2014-03-28,201413,2014,12,120040,1938.0,2001527.0,2014-03-23,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508648,2,A90,20231228,202352,2023,17,172120,NaN,9038701.0,20231226,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1986.0,20240104,NaN
1508649,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1984.0,20231229,NaN
1508650,2,A90,20231229,202352,2023,17,170820,NaN,2546728.0,20231225,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1971.0,20240119,NaN
1508651,2,A90,20231229,202352,2023,17,170700,NaN,2786095.0,20231228,...,NaN,NaN,NaN,2.0,NaN,1.0,NaN,1996.0,20231229,NaN
1508652,2,A90,20231229,202352,2023,17,172100,NaN,5144175.0,20231222,...,NaN,NaN,NaN,2.0,NaN,0.0,NaN,1959.0,20231229,NaN

In [7]:
from pysus import SINAN
sinan = SINAN().load() # Loads the files from DATASUS

In [9]:
codigo_ilheus_itabna = [291480,291360]
deng_dados14_ba = deng_dados14[deng_dados14['ID_MUNICIP'].isin(codigo_ilheus_itabna)]
deng_dados14_ba

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI
67512,2,A90,2014-07-07,201428,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67516,2,A90,2014-07-14,201429,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67517,2,A90,2014-04-23,201417,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67518,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
67519,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92126,2,A90,2014-03-24,201413,2014,29,291480,1385.0,2772280.0,2014-03-22,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92138,2,A90,2014-03-31,201414,2014,29,291480,1385.0,2772280.0,2014-03-27,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92147,2,A90,2014-03-07,201410,2014,29,291360,1385.0,2415844.0,2014-03-04,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
92172,2,A90,2014-03-20,201412,2014,29,291360,1385.0,2415844.0,2014-03-20,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,NaN
92226,2,A90,2014-03-18,201412,2014,29,291480,1385.0,2772280.0,2014-03-15,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN

In [15]:
# deng_dados23.NU_IDADE_N.value_counts()
# for cname in deng_dados23.columns:
#     if cname.startswith('DT_'):
#         deng_dados23[cname] = pd.to_datetime(deng_dados23[cname], errors='coerce')
#     elif cname.startswith('ID_'):
#         try:
#             deng_dados23[cname] = pd.to_numeric(deng_dados23[cname])
#         except ValueError:
#             continue
# deng_dados23.info()

### Leitura da base de dados filtrada

Leitura dados 2014

In [23]:
deng_2014 = pd.read_csv('./data-filtred/deng_dados14_ba.csv')
deng_2014

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI
0,2,A90,2014-07-07,201428,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
1,2,A90,2014-07-14,201429,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
2,2,A90,2014-04-23,201417,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
3,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
4,2,A90,2014-01-24,201404,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2141,2,A90,2014-03-24,201413,2014,29,291480,1385.0,2772280.0,2014-03-22,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
2142,2,A90,2014-03-31,201414,2014,29,291480,1385.0,2772280.0,2014-03-27,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
2143,2,A90,2014-03-07,201410,2014,29,291360,1385.0,2415844.0,2014-03-04,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
2144,2,A90,2014-03-20,201412,2014,29,291360,1385.0,2415844.0,2014-03-20,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,NaN
2145,2,A90,2014-03-18,201412,2014,29,291480,1385.0,2772280.0,2014-03-15,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN

In [14]:
deng_2014.NU_IDADE_N.value_counts()

NU_IDADE_N
4020.0    66
4026.0    62
4027.0    61
4021.0    60
4033.0    59
          ..
3009.0     1
4081.0     1
3005.0     1
4089.0     1
4084.0     1
Name: count, Length: 100, dtype: int64

In [ ]:

for cname in deng_2014.columns:
    if cname.startswith('DT_'):
        deng_2014[cname] = pd.to_datetime(deng_2014[cname], errors='coerce')
    elif cname.startswith('ID_'):
        try:
            deng_2014[cname] = pd.to_numeric(deng_2014[cname])
        except ValueError:
            continue

In [11]:
from pysus.preprocessing.decoders import decodifica_idade_SINAN

In [17]:
deng_2014['idade_anos'] = decodifica_idade_SINAN(
    deng_2014['NU_IDADE_N'],
    unidade='Y'
)

In [7]:
deng_dados25 = pd.read_csv('../data/nao-processado/DENGBR25.csv')
codigo_ilheus_itabna = [291360,291480]

deng_dados25_ba = deng_dados25[deng_dados25['ID_MUNICIP'].isin(codigo_ilheus_itabna)]

/tmp/ipykernel_39014/3914837381.py:1: DtypeWarning: Columns (5,21,22,117) have mixed types. Specify dtype option on import or set low_memory=False.
  deng_dados25 = pd.read_csv('../data/nao-processado/DENGBR25.csv')

In [33]:
deng_dados25_ba.to_csv('../data/processado/deng_dados25_ba.csv', index=False)

In [36]:
import glob

path = '../data/processado/*.csv'

arquivos = glob.glob(path)

lista_dfs = [pd.read_csv(arq) for arq in arquivos]
df_deng_total = pd.concat(lista_dfs, ignore_index=True)

/tmp/ipykernel_39014/3852709408.py:7: DtypeWarning: Columns (9,21,75) have mixed types. Specify dtype option on import or set low_memory=False.
  lista_dfs = [pd.read_csv(arq) for arq in arquivos]
/tmp/ipykernel_39014/3852709408.py:7: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  lista_dfs = [pd.read_csv(arq) for arq in arquivos]

In [14]:
df_deng_total.NU_IDADE_N.value_counts()

NU_IDADE_N
4022.0    313
4024.0    297
4023.0    297
4021.0    296
4027.0    286
         ...
18.0        1
2009.0      1
2024.0      1
37.0        1
2019.0      1
Name: count, Length: 130, dtype: int64

In [37]:
df_deng_total['idade_anos'] = None

mask = df_deng_total['NU_IDADE_N'].notna()

df_deng_total.loc[mask, 'idade_anos'] = decodifica_idade_SINAN(
    df_deng_total.loc[mask, 'NU_IDADE_N'],
    unidade='Y'
)
df_deng_total.idade_anos.value_counts()

idade_anos
21.000000    473
22.000000    466
24.000000    448
19.000000    447
23.000000    445
            ...
0.054795       1
0.038356       1
93.000000      1
0.046575       1
0.065753       1
Name: count, Length: 135, dtype: int64

In [38]:
df_deng_total.to_csv('../data/final/df_deng_total.csv', index=False)

In [39]:
df_deng_total = pd.read_csv('../data/final/df_deng_total.csv')

/tmp/ipykernel_39014/1746610790.py:1: DtypeWarning: Columns (2,5,9,22,120) have mixed types. Specify dtype option on import or set low_memory=False.
  df_deng_total = pd.read_csv('../data/final/df_deng_total.csv')

In [40]:
df_deng_total

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W,idade_anos
0,2,A90,2014-07-07,201428.0,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,43.0
1,2,A90,2014-07-14,201429.0,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,20.0
2,2,A90,2014-04-23,201417.0,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,6.0
3,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,50.0
4,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63287,2,A90,20240820,202434.0,2024,29,291360,1385.0,2939363.0,20240810,...,NaN,NaN,NaN,NaN,1.0,NaN,2012.0,,NaN,12.0
63288,2,A90,20240507,202419.0,2024,29,291360,1385.0,2939363.0,20240504,...,NaN,NaN,2.0,NaN,1.0,NaN,2001.0,20240514,NaN,23.0
63289,2,A90,20240404,202414.0,2024,29,291360,1385.0,2415844.0,20240403,...,NaN,NaN,2.0,NaN,1.0,NaN,2021.0,20240408,NaN,2.0
63290,2,A90,20240507,202419.0,2024,29,291360,1385.0,2939363.0,20240503,...,NaN,NaN,2.0,NaN,1.0,NaN,1998.0,20240514,NaN,26.0
63291,2,A90,20240521,202421.0,2024,29,291360,1385.0,2939363.0,20240514,...,NaN,NaN,2.0,NaN,1.0,NaN,2008.0,20240627,NaN,16.0

## Verificando os anos e quantidade de valores existentes para cada ano

In [48]:
# Lista quantos registros existem para cada ano
print(df_deng_total['NU_ANO'].value_counts())

NU_ANO
2016    25549
2015    14860
2025     5461
2024     3949
2022     3513
2023     2430
2014     2136
2020     1709
2019     1255
2017     1096
2021      809
2018      505
2026       14
2013        6
Name: count, dtype: int64

In [49]:
df_deng_total.describe()

,TP_NOT,SEM_NOT,NU_ANO,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,SEM_PRI,NU_IDADE_N,CS_GESTANT,CS_RACA,...,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,MIGRADO_W,idade_anos
count,63292.0,61577.000000,63292.000000,63292.000000,63292.0,6.328900e+04,63291.000000,18319.000000,63276.000000,57281.000000,...,1.0,0.0,0.0,22352.0,0.0,58973.000000,1.0,15979.000000,0.0,18314.000000
mean,2.0,201795.197428,2017.841797,291438.914239,1385.0,3.313334e+06,201792.421292,4005.701403,6.422878,6.863969,...,1000.0,NaN,NaN,2.0,NaN,0.546148,2.0,1993.072095,NaN,30.007554
std,0.0,363.982539,3.583507,56.941222,0.0,2.012061e+06,409.797998,202.813836,1.316441,2.793729,...,NaN,NaN,NaN,0.0,NaN,0.498347,NaN,18.989333,NaN,19.016761
min,2.0,201401.000000,2013.000000,291360.000000,1385.0,2.184176e+06,193333.000000,4.000000,1.000000,1.000000,...,1000.0,NaN,NaN,2.0,NaN,0.000000,2.0,1920.000000,NaN,0.002740
25%,2.0,201549.000000,2015.000000,291360.000000,1385.0,2.470349e+06,201549.000000,4016.000000,6.000000,4.000000,...,1000.0,NaN,NaN,2.0,NaN,0.000000,2.0,1981.000000,NaN,16.000000
50%,2.0,201609.000000,2016.000000,291480.000000,1385.0,2.525569e+06,201609.000000,4027.000000,6.000000,9.000000,...,1000.0,NaN,NaN,2.0,NaN,1.000000,2.0,1996.000000,NaN,27.000000
75%,2.0,202150.000000,2021.000000,291480.000000,1385.0,2.772280e+06,202118.000000,4042.000000,6.000000,9.000000,...,1000.0,NaN,NaN,2.0,NaN,1.000000,2.0,2008.000000,NaN,42.000000
max,2.0,202603.000000,2026.000000,291480.000000,1385.0,9.993703e+06,202553.000000,4406.000000,9.000000,9.000000,...,1000.0,NaN,NaN,2.0,NaN,5.000000,2.0,2025.000000,NaN,406.000000

### Analise de campos para entender disposição de dados

In [63]:
print(df_deng_total['EVOLUCAO'].value_counts())
print(df_deng_total['CS_SEXO'].value_counts())
print(df_deng_total['CLASSI_FIN'].value_counts())
print(df_deng_total['CS_SEXO'].value_counts())

EVOLUCAO
1.0    44428
9.0      109
3.0       38
2.0        9
4.0        2
Name: count, dtype: int64
CS_SEXO
F    35982
M    27017
I      286
Name: count, dtype: int64
CLASSI_FIN
10.0    43293
8.0     13413
5.0      5481
1.0       618
11.0      194
12.0       29
Name: count, dtype: int64
CS_SEXO
F    35982
M    27017
I      286
Name: count, dtype: int64

- Isso indica que a maioria dos casos evoluiu para cura e alguns casos teve obito pelo agravo ou outros fatores
- Maior casos em mulheres
- Classificacao final sendo em sua maioria casos de dengue comum e alguns casos descartados (não se sabe o que é a classificação 8) 
- O que sera feito com os dados do sexo I(ignorado), matem ou remove?

## Tranformando campos do dataframe em campos legiveis

In [68]:
from pysus.online_data import SINAN
metadata = SINAN.metadata_df('DENG')
dicionario = dict(zip(metadata['DBF'], metadata['Nome do campo']))
dicionario

{'ID_AGRAVO': '2-Agravo/doença',
 'DT_INVEST': '31-Data da Investigação',
 'ID_OCUPA_N': '32- Ocupação/ramo de atividade econômica',
 'FEBRE': '33- Sinais clínicos (Febre)',
 'MIALGIA': '33- Sinais clínicos (Mialgia)',
 'CEFALEIA': '33- Sinais clínicos (Cefaleia)',
 'EXANTEMA': '33- Sinais clínicos (Exantema)',
 'VOMITO': '33- Sinais clínicos (Vômito)',
 'NAUSEA': '33- Sinais clínicos (Náusea)',
 'DOR_COSTAS': '33- Sinais clínicos (Dor nas costas)',
 'CONJUNTVIT': '33- Sinais clínicos (Conjuntivite)',
 'ARTRITE': '33- Sinais clínicos (Artrite)',
 'ARTRALGIA': '33- Sinais clínicos (Artralgia intensa)',
 'PETÉQUIA_N': '33- Sinais clínicos (Petéquias)',
 'LEUCOPENIA': '33- Sinais clínicos (Leucopenia)',
 'LACO': '33- Sinais clínicos (Prova do laço)',
 'DOR_RETRO': '33- Sinais clínicos (Dor retroorbital)',
 'DIABETES': '34- Doenças pré- existentes (Diabetes)',
 'HEMATOLOG': '34- Doenças pré- existentes (Doenças hematológicas)',
 'HEPATOPAT': '34- Doenças pré- existentes (Hepatopatias)',
 'RENAL': '34- Doenças pré- existentes (Doença renal crônica)',
 'HIPERTENSA': '34- Doenças pré- existentes (Hipertensão arterial)',
 'ÁCIDO_PEPT': '34- Doenças pré- existentes (Doença ácido-péptica)',
 'AUTO_IMUNE': '34- Doenças pré- existentes (Doenças auto-imunes)',
 'DT_CHIK_S1': '35-Exame sorológico (IgM) Chikungunya Soro 1 Data da Coleta',
 'DT_CHIK_S2': '36-Exame sorológico (IgM) Chikungunya Soro 2 Data da Coleta',
 'DT_PRNT': '37-Exame PRNT Data da Coleta',
 'RES_CHIKS1': '38-Exame sorológico (IgM) Chikungunya Soro 1 Resultado',
 'RES_CHIKS2': '38-Exame sorológico (IgM) Chikungunya Soro 2 Resultado',
 'RESUL_PRNT': '38-Exame PRNT Resultado',
 'DT_SORO': '39-Exame sorológico (IgM) Dengue Data da Coleta',
 'RESUL_SORO': '40-Exame sorológico (IgM) Dengue Resultado',
 'DT_NS1': '41- Exame NS1 Data da Coleta',
 'RESUL_NS1': '42- Exame NS1 Resultado',
 'DT_VIRAL': '43-Isolamento Viral Data da Coleta',
 'RESUL_VI_N': '43-Isolamento Viral Resultado',
 'DT_PCR': '45-RT-PCR Data da Coleta',
 'RESUL_PCR_': '46-RT-PCR Resultado',
 'SOROTIPO': '47-Sorotipo',
 'HISTOPA_N': '48-Histopatologia Resultado',
 'IMUNOH_N': '49-Imunohistoquímica Resultado',
 'HOSPITALIZ': '50-Ocorreu Hospitalização?',
 'DT_INTERNA': '51-Data Da Internação',
 'UF': '52-UF De Hospitalização',
 'MUNICIPIO': '53-Municipio Do Hospital',
 'HOSPITAL': '54-Nome Do Hospital',
 'DDD_HOSP': '55-(DDD)',
 'TEL_HOSP': '55-Telefone',
 'TPAUTOCTO': '56-O caso é Autóctone de residência?',
 'COUFINF': '57-UF (provável da fonte de infecção)',
 'COPAISINF': '58-País (provável da fonte de infecção)',
 'COMUNINF': '59-Município (provável da fonte de infecção)',
 'CODISINF': '60-Distrito (provável de infecção)',
 'CO_BAINF\nNOBAIINF': '61-Bairro (provável de infecção)',
 'CLASSI_FIN': '62-Classificação',
 'CRITERIO': '63-Critério De Confirmação/Descarte',
 'CLINIC_CHIK': '64- Apresentação clínica Chikungunya',
 'EVOLUCAO': '65-Evolução Do Caso',
 'DT_OBITO': '66-Data do Óbito',
 'DT_ENCERRA': '67-Data Do Encerramento',
 'ALRM_HIPOT': '68- Dengue com sinais de alarme (Hipotensão)',
 'ALRM_PLAQ': '68- Dengue com sinais de alarme (Queda abrupta de plaquetas)',
 'ALRM_VOM': '68- Dengue com sinais de alarme (Vômitos persistentes)',
 'ALRM_ABDOM': '68- Dengue com sinais de alarme (Dor abdominal)',
 'ALRM_LETAR': '68- Dengue com sinais de alarme (Letargia ou irritabilidade)',
 'ALRM_SANG': '68- Dengue com sinais de alarme (Sangramento de mucosa/outras hemorragias)',
 'ALRM_HEMAT': '68- Dengue com sinais de alarme (Aumento hematócrito)',
 'ALRM_HEPAT': '68- Dengue com sinais de alarme (Hepatomegalia)',
 'ALRM_LIQ': '68- Dengue com sinais de alarme (Acúmulo de líquidos)',
 'DT_ALRM': '69- Dengue com sinais de alarme Data de início dos sintomas',
 'GRAV_PULSO': '70- Dengue grave (Pulso débil ou indectável)',
 'GRAV_CONV': '70- Dengue grave (PA convergente)',
 'GRAV_ENCH': '70- Dengue grave (Tempo de enchimento capilar)',
 'GRAV_INSUF': '70- Dengue grave (Acúmulo de líquidos com insuficiência respiratória)',
 'GRAV_TAQUI': '70- Dengue grave (Taquicardia)',
 'GRAV_EXTRE': '70- Dengue grave (Extremidade frias)',
 'GRAV_HIPOT': '70- Dengue grave (Hipotensão arterial em fase tardia)',
 'GRAV_HEMAT': '70- Dengue grave (Hematêmese)',
 'GRAV_MELEN': '70- Dengue grave (Melena)',
 'GRAV_METRO': '70- Dengue grave (Metrorragia volumosa)',
 'GRAV_SANG': '70- Dengue grave (Sangramento do SNC)',
 'GRAV_AST': '70- Dengue grave (AST/ALT >1 .000)',
 'GRAV_MIOC': '70- Dengue grave (Miocardite)',
 'GRAV_CONSC': '70- Dengue grave (Alteração da consciência)',
 'GRAV_ORGAO': '70- Dengue grave (Outros órgãos)',
 'DT_GRAV': '71- Dengue grave Data de início dos sintomas',
 'DS_OBS': 'Informações complementares e observações adicionais',
 nan: nan}

In [110]:
import json
with open('../src/dicionario-campos.json', 'r') as f:
    dic_colunas_dengue = json.load(f)
dic_colunas_dengue

{'TP_NOT': 'tipo_notificacao',
 'ID_AGRAVO': 'codigo_agravo',
 'DT_NOTIFIC': 'data_notificacao',
 'SEM_NOT': 'semana_notificacao',
 'NU_ANO': 'ano_notificacao',
 'SG_UF_NOT': 'uf_notificacao',
 'ID_MUNICIP': 'municipio_notificacao',
 'ID_REGIONA': 'regional_notificacao',
 'ID_UNIDADE': 'unidade_notificacao',
 'DT_SIN_PRI': 'data_primeiros_sintomas',
 'SEM_PRI': 'semana_primeiros_sintomas',
 'DT_NASC': 'data_nascimento',
 'NU_IDADE_N': 'idade_sinan',
 'CS_SEXO': 'sexo',
 'CS_GESTANT': 'gestante',
 'CS_RACA': 'raca_cor',
 'CS_ESCOL_N': 'escolaridade',
 'SG_UF': 'uf_residencia',
 'ID_MN_RESI': 'municipio_residencia',
 'ID_RG_RESI': 'regional_residencia',
 'ID_PAIS': 'pais_residencia',
 'DT_INVEST': 'data_investigacao',
 'ID_OCUPA_N': 'ocupacao',
 'FEBRE': 'febre',
 'MIALGIA': 'mialgia',
 'CEFALEIA': 'cefaleia',
 'EXANTEMA': 'exantema',
 'VOMITO': 'vomito',
 'NAUSEA': 'nausea',
 'DOR_COSTAS': 'dor_costas',
 'CONJUNTVIT': 'conjuntivite',
 'ARTRITE': 'artrite',
 'ARTRALGIA': 'artralgia',
 'PETEQUIA_N': 'petequias',
 'LEUCOPENIA': 'leucopenia',
 'LACO': 'prova_laco',
 'DOR_RETRO': 'dor_retroorbital',
 'DIABETES': 'diabetes',
 'HEMATOLOG': 'doenca_hematologica',
 'HEPATOPAT': 'doenca_hepatica',
 'RENAL': 'doenca_renal',
 'HIPERTENSA': 'hipertensao',
 'ACIDO_PEPT': 'ulcera_peptica',
 'AUTO_IMUNE': 'doenca_autoimune',
 'DT_CHIK_S1': 'data_sorologia_chik1',
 'DT_CHIK_S2': 'data_sorologia_chik2',
 'DT_PRNT': 'data_prnt',
 'RES_CHIKS1': 'resultado_chik1',
 'RES_CHIKS2': 'resultado_chik2',
 'RESUL_PRNT': 'resultado_prnt',
 'DT_SORO': 'data_sorologia',
 'RESUL_SORO': 'resultado_sorologia',
 'DT_NS1': 'data_ns1',
 'RESUL_NS1': 'resultado_ns1',
 'DT_VIRAL': 'data_isolamento_viral',
 'RESUL_VI_N': 'resultado_isolamento_viral',
 'DT_PCR': 'data_pcr',
 'RESUL_PCR_': 'resultado_pcr',
 'SOROTIPO': 'sorotipo_dengue',
 'HISTOPA_N': 'histopatologia',
 'IMUNOH_N': 'imunohistoquimica',
 'HOSPITALIZ': 'hospitalizacao',
 'DT_INTERNA': 'data_internacao',
 'UF': 'uf_infeccao',
 'MUNICIPIO': 'municipio_infeccao',
 'TPAUTOCTO': 'caso_autoctone',
 'COUFINF': 'uf_infeccao_codigo',
 'COPAISINF': 'pais_infeccao',
 'COMUNINF': 'municipio_infeccao_nome',
 'CLASSI_FIN': 'classificacao_final',
 'CRITERIO': 'criterio_confirmacao',
 'DOENCA_TRA': 'doenca_relacionada',
 'CLINC_CHIK': 'clinica_chikungunya',
 'EVOLUCAO': 'evolucao_caso',
 'DT_OBITO': 'data_obito',
 'DT_ENCERRA': 'data_encerramento',
 'ALRM_HIPOT': 'alarme_hipotensao',
 'ALRM_PLAQ': 'alarme_plaquetas',
 'ALRM_VOM': 'alarme_vomito',
 'ALRM_SANG': 'alarme_sangramento',
 'ALRM_HEMAT': 'alarme_hematocrito',
 'ALRM_ABDOM': 'alarme_dor_abdominal',
 'ALRM_LETAR': 'alarme_letargia',
 'ALRM_HEPAT': 'alarme_hepatomegalia',
 'ALRM_LIQ': 'alarme_liquidos',
 'DT_ALRM': 'data_sinais_alarme',
 'GRAV_PULSO': 'gravidade_pulso',
 'GRAV_CONV': 'gravidade_convulsao',
 'GRAV_ENCH': 'gravidade_enchimento_capilar',
 'GRAV_INSUF': 'gravidade_insuficiencia',
 'GRAV_TAQUI': 'gravidade_taquicardia',
 'GRAV_EXTRE': 'gravidade_extremidades',
 'GRAV_HIPOT': 'gravidade_hipotensao',
 'GRAV_HEMAT': 'gravidade_hematemese',
 'GRAV_MELEN': 'gravidade_melena',
 'GRAV_METRO': 'gravidade_metrorragia',
 'GRAV_SANG': 'gravidade_sangramento',
 'GRAV_AST': 'gravidade_ast',
 'GRAV_MIOC': 'gravidade_miocardite',
 'GRAV_CONSC': 'gravidade_consciencia',
 'GRAV_ORGAO': 'gravidade_orgao',
 'DT_GRAV': 'data_dengue_grave',
 'MANI_HEMOR': 'manifestacao_hemorragica',
 'EPISTAXE': 'epistaxe',
 'GENGIVO': 'sangramento_gengival',
 'METRO': 'metrorragia',
 'PETEQUIAS': 'petequias_hemorragicas',
 'HEMATURA': 'hematúria',
 'SANGRAM': 'sangramento',
 'LACO_N': 'prova_laco_numero',
 'PLASMATICO': 'extravasamento_plasmatico',
 'EVIDENCIA': 'evidencia_clinica',
 'PLAQ_MENOR': 'plaquetas_menor_100k',
 'CON_FHD': 'confirmacao_febre_hemorragica',
 'COMPLICA': 'complicacoes',
 'TP_SISTEMA': 'tipo_sistema',
 'NDUPLIC_N': 'numero_duplicidade',
 'CS_FLXRET': 'fluxo_retorno',
 'FLXRECEBI': 'fluxo_recebimento',
 'ANO_NASC': 'ano_nascimento',
 'DT_DIGITA': 'data_digitacao',
 'MIGRADO_W': 'registro_migrado',
 'idade_anos': 'idade_anos'}

In [81]:
colunas = df_deng_total.columns.tolist()
colunas

['TP_NOT',
 'ID_AGRAVO',
 'DT_NOTIFIC',
 'SEM_NOT',
 'NU_ANO',
 'SG_UF_NOT',
 'ID_MUNICIP',
 'ID_REGIONA',
 'ID_UNIDADE',
 'DT_SIN_PRI',
 'SEM_PRI',
 'DT_NASC',
 'NU_IDADE_N',
 'CS_SEXO',
 'CS_GESTANT',
 'CS_RACA',
 'CS_ESCOL_N',
 'SG_UF',
 'ID_MN_RESI',
 'ID_RG_RESI',
 'ID_PAIS',
 'DT_INVEST',
 'ID_OCUPA_N',
 'FEBRE',
 'MIALGIA',
 'CEFALEIA',
 'EXANTEMA',
 'VOMITO',
 'NAUSEA',
 'DOR_COSTAS',
 'CONJUNTVIT',
 'ARTRITE',
 'ARTRALGIA',
 'PETEQUIA_N',
 'LEUCOPENIA',
 'LACO',
 'DOR_RETRO',
 'DIABETES',
 'HEMATOLOG',
 'HEPATOPAT',
 'RENAL',
 'HIPERTENSA',
 'ACIDO_PEPT',
 'AUTO_IMUNE',
 'DT_CHIK_S1',
 'DT_CHIK_S2',
 'DT_PRNT',
 'RES_CHIKS1',
 'RES_CHIKS2',
 'RESUL_PRNT',
 'DT_SORO',
 'RESUL_SORO',
 'DT_NS1',
 'RESUL_NS1',
 'DT_VIRAL',
 'RESUL_VI_N',
 'DT_PCR',
 'RESUL_PCR_',
 'SOROTIPO',
 'HISTOPA_N',
 'IMUNOH_N',
 'HOSPITALIZ',
 'DT_INTERNA',
 'UF',
 'MUNICIPIO',
 'TPAUTOCTO',
 'COUFINF',
 'COPAISINF',
 'COMUNINF',
 'CLASSI_FIN',
 'CRITERIO',
 'DOENCA_TRA',
 'CLINC_CHIK',
 'EVOLUCAO',
 'DT_OBITO',
 'DT_ENCERRA',
 'ALRM_HIPOT',
 'ALRM_PLAQ',
 'ALRM_VOM',
 'ALRM_SANG',
 'ALRM_HEMAT',
 'ALRM_ABDOM',
 'ALRM_LETAR',
 'ALRM_HEPAT',
 'ALRM_LIQ',
 'DT_ALRM',
 'GRAV_PULSO',
 'GRAV_CONV',
 'GRAV_ENCH',
 'GRAV_INSUF',
 'GRAV_TAQUI',
 'GRAV_EXTRE',
 'GRAV_HIPOT',
 'GRAV_HEMAT',
 'GRAV_MELEN',
 'GRAV_METRO',
 'GRAV_SANG',
 'GRAV_AST',
 'GRAV_MIOC',
 'GRAV_CONSC',
 'GRAV_ORGAO',
 'DT_GRAV',
 'MANI_HEMOR',
 'EPISTAXE',
 'GENGIVO',
 'METRO',
 'PETEQUIAS',
 'HEMATURA',
 'SANGRAM',
 'LACO_N',
 'PLASMATICO',
 'EVIDENCIA',
 'PLAQ_MENOR',
 'CON_FHD',
 'COMPLICA',
 'TP_SISTEMA',
 'NDUPLIC_N',
 'CS_FLXRET',
 'FLXRECEBI',
 'ANO_NASC',
 'DT_DIGITA',
 'MIGRADO_W',
 'idade_anos']

In [103]:
df_deng_total_ren = df_deng_total.rename(columns=dic_colunas_dengue)
df_deng_total_ren

,tipo_notificacao,codigo_agravo,data_notificacao,semana_notificacao,ano_notificacao,uf_notificacao,municipio_notificacao,regional_notificacao,unidade_notificacao,data_primeiros_sintomas,...,confirmacao_febre_hemorragica,complicacoes,tipo_sistema,numero_duplicidade,fluxo_retorno,fluxo_recebimento,ano_nascimento,data_digitacao,registro_migrado,idade_anos
0,2,A90,2014-07-07,201428.0,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,43.0
1,2,A90,2014-07-14,201429.0,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,20.0
2,2,A90,2014-04-23,201417.0,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,6.0
3,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,50.0
4,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63287,2,A90,20240820,202434.0,2024,29,291360,1385.0,2939363.0,20240810,...,NaN,NaN,NaN,NaN,1.0,NaN,2012.0,,NaN,12.0
63288,2,A90,20240507,202419.0,2024,29,291360,1385.0,2939363.0,20240504,...,NaN,NaN,2.0,NaN,1.0,NaN,2001.0,20240514,NaN,23.0
63289,2,A90,20240404,202414.0,2024,29,291360,1385.0,2415844.0,20240403,...,NaN,NaN,2.0,NaN,1.0,NaN,2021.0,20240408,NaN,2.0
63290,2,A90,20240507,202419.0,2024,29,291360,1385.0,2939363.0,20240503,...,NaN,NaN,2.0,NaN,1.0,NaN,1998.0,20240514,NaN,26.0
63291,2,A90,20240521,202421.0,2024,29,291360,1385.0,2939363.0,20240514,...,NaN,NaN,2.0,NaN,1.0,NaN,2008.0,20240627,NaN,16.0

## Padronizar datas

- Primeiro criar uma função
- Transforma o valor recebido para string
- Caso tenha 8 caracteres e nao esteja no formato YYYY-MM-DD vai formatar corretamente

In [ ]:
def parse_data(val):
    val = str(val).strip()
    if len(val) == 8 and '-' not in val:  # formato YYYYMMDD
        return pd.to_datetime(val, format='%Y%m%d')
    return pd.to_datetime(val)  # formato já correto

df_deng_total_ren['data_notificacao'] = df_deng_total_ren['data_notificacao'].apply(parse_data)

In [106]:
df_deng_total_ren

,tipo_notificacao,codigo_agravo,data_notificacao,semana_notificacao,ano_notificacao,uf_notificacao,municipio_notificacao,regional_notificacao,unidade_notificacao,data_primeiros_sintomas,...,confirmacao_febre_hemorragica,complicacoes,tipo_sistema,numero_duplicidade,fluxo_retorno,fluxo_recebimento,ano_nascimento,data_digitacao,registro_migrado,idade_anos
0,2,A90,2014-07-07,201428.0,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,43.0
1,2,A90,2014-07-14,201429.0,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,20.0
2,2,A90,2014-04-23,201417.0,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,6.0
3,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,50.0
4,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63287,2,A90,2024-08-20,202434.0,2024,29,291360,1385.0,2939363.0,20240810,...,NaN,NaN,NaN,NaN,1.0,NaN,2012.0,,NaN,12.0
63288,2,A90,2024-05-07,202419.0,2024,29,291360,1385.0,2939363.0,20240504,...,NaN,NaN,2.0,NaN,1.0,NaN,2001.0,20240514,NaN,23.0
63289,2,A90,2024-04-04,202414.0,2024,29,291360,1385.0,2415844.0,20240403,...,NaN,NaN,2.0,NaN,1.0,NaN,2021.0,20240408,NaN,2.0
63290,2,A90,2024-05-07,202419.0,2024,29,291360,1385.0,2939363.0,20240503,...,NaN,NaN,2.0,NaN,1.0,NaN,1998.0,20240514,NaN,26.0
63291,2,A90,2024-05-21,202421.0,2024,29,291360,1385.0,2939363.0,20240514,...,NaN,NaN,2.0,NaN,1.0,NaN,2008.0,20240627,NaN,16.0

### Definir faixa etária para os dados analisados para facilitar leitura e interpretação

In [112]:
bins = [0,1,5,10,20,40,60,80,120]
labels = ['<1','1-4','5-9','10-19','20-39','40-59','60-79','80+']

df_deng_total_ren['faixa_etaria'] = pd.cut(df_deng_total_ren['idade_anos'],bins=bins, labels=labels)
df_deng_total_ren

,tipo_notificacao,codigo_agravo,data_notificacao,semana_notificacao,ano_notificacao,uf_notificacao,municipio_notificacao,regional_notificacao,unidade_notificacao,data_primeiros_sintomas,...,complicacoes,tipo_sistema,numero_duplicidade,fluxo_retorno,fluxo_recebimento,ano_nascimento,data_digitacao,registro_migrado,idade_anos,faixa_etaria
0,2,A90,2014-07-07,201428.0,2014,29,291480,1385.0,2385171.0,2014-07-01,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,43.0,40-59
1,2,A90,2014-07-14,201429.0,2014,29,291480,1385.0,2385171.0,2014-07-07,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,20.0,10-19
2,2,A90,2014-04-23,201417.0,2014,29,291480,1385.0,2525569.0,2014-04-21,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,6.0,5-9
3,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2772280.0,2014-01-23,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,50.0,40-59
4,2,A90,2014-01-24,201404.0,2014,29,291480,1385.0,2385171.0,2014-01-17,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,44.0,40-59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63287,2,A90,2024-08-20,202434.0,2024,29,291360,1385.0,2939363.0,20240810,...,NaN,NaN,NaN,1.0,NaN,2012.0,,NaN,12.0,10-19
63288,2,A90,2024-05-07,202419.0,2024,29,291360,1385.0,2939363.0,20240504,...,NaN,2.0,NaN,1.0,NaN,2001.0,20240514,NaN,23.0,20-39
63289,2,A90,2024-04-04,202414.0,2024,29,291360,1385.0,2415844.0,20240403,...,NaN,2.0,NaN,1.0,NaN,2021.0,20240408,NaN,2.0,1-4
63290,2,A90,2024-05-07,202419.0,2024,29,291360,1385.0,2939363.0,20240503,...,NaN,2.0,NaN,1.0,NaN,1998.0,20240514,NaN,26.0,20-39
63291,2,A90,2024-05-21,202421.0,2024,29,291360,1385.0,2939363.0,20240514,...,NaN,2.0,NaN,1.0,NaN,2008.0,20240627,NaN,16.0,10-19

In [113]:
df_deng_total_ren.to_csv('../data/final/df_deng_padrao.csv', index=False)